Fix namespace, identifier-type and system per issue #773
GSA/automate.fedramp.gov pull request #102
Opened 2024-10-28 19:59 UTC by Rene2mt

This PR address website documentation updates to resolve issue GSA/fedramp-automation/issues/773 

Specifically, it makes the following changes throughout the site:
- For FedRAMP extension properties, changes namespace from "**https**://fedramp.gov/ns/oscal" to "**http**://fedramp.gov/ns/oscal"
- For the SSP `identifier-type`, changes the value from "**https**://fedramp.gov/ns/oscal" to "**http**://fedramp.gov/ns/oscal"
- For POA&M facets, changes the `system` flag from "**https**://fedramp.gov" to "**http**://fedramp.gov/ns/oscal"

2024-12-13 22:35 UTC, aj-stein-gsa requested changes
I would approve with the quote issue, but I wary of moving up submodules for site components with content edits unless there is a reason.

2024-12-13 22:35 UTC, aj-stein-gsa commented on themes/uswds-hugo
Blocking: can we back out submodules changes unless there is a pressing reason you can explain it in a follow-up comment?

2024-12-16 15:49 UTC, Rene2mt commented on themes/uswds-hugo
will do...I unintentionally committed a submodule change

2024-12-17 01:47 UTC, aj-stein-gsa approved these changes

2024-12-17 16:09 UTC, Gabeblis approved these changes

2024-12-20 23:33 UTC, aj-stein-gsa commented
If you are a community member subscribed to notifications outside of the developer team, be advised we are readying this for merge and publication. An email will be sent to pilot participants as well when this is complete, but this is a heads up that process is starting.

2024-12-20 23:35 UTC, merged