Update oscal-metadata.md
GSA/automate.fedramp.gov pull request #112
Opened 2024-11-14 19:08 UTC by wandmagic

2024-11-14 19:14 UTC, Gabeblis approved these changes

2024-11-14 19:33 UTC, aj-stein-gsa requested changes

2024-11-14 19:33 UTC, aj-stein-gsa commented on content/documentation/general-concepts/oscal-metadata.md
> +is required for all parties.
I would slightly adjust this, but thanks for adding the documentation and missing the constraint gap.

```suggestion
required for the CSP, assessor, and any Agency. A party's `name` field 
is required for all parties.
```

2024-11-15 15:31 UTC, aj-stein-gsa approved these changes
I would add an "a" in the cleanup before merge, but thanks for taking care of this so quickly.

2024-11-15 15:31 UTC, aj-stein-gsa commented on content/documentation/general-concepts/oscal-metadata.md
> +within FedRAMP artifacts. All parties require `name` field.
Very minor nit, but I approve.

```suggestion
within FedRAMP artifacts. All parties require a `name` field. 
```

2024-11-18 13:52 UTC, Rene2mt approved these changes

2024-11-18 13:55 UTC, merged