Add allowed values for the nature-of-agreement property
GSA/automate.fedramp.gov pull request #122
Opened 2024-11-21 16:11 UTC by DimitriZhurkin

In the **Leveraged FedRAMP-authorized Services** section, add allowed values for the `nature-of-agreement` property.

2024-11-21 16:40 UTC, DimitriZhurkin commented
Related PR: [#920](https://github.com/GSA/fedramp-automation/pull/920)

2024-11-21 18:08 UTC, wandmagic approved these changes

2024-11-21 18:47 UTC, Gabeblis requested changes
Just a couple suggestions for consistency.

2024-11-21 19:43 UTC, DimitriZhurkin commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +##### FedRAMP Allowed Values
Fixed.

2024-11-21 19:43 UTC, DimitriZhurkin commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +
Moved the explanation up.

2024-11-22 13:31 UTC, Gabeblis approved these changes

2024-11-22 14:02 UTC, aj-stein-gsa reviewed
We are going to start using callouts for allowed-value enumeration sets?

2024-11-22 15:00 UTC, aj-stein-gsa commented
> > We are going to start using callouts for allowed-value enumeration sets?
> 
> 
> 
> We have been using callouts for allowed-value enumeration sets up to this point. Should this be changed? 

That's ok I just didn't quickly find an example.

2024-11-22 15:00 UTC, aj-stein-gsa approved these changes

2024-11-22 15:04 UTC, merged