Add Leveraged-Authorization Documentation
GSA/automate.fedramp.gov pull request #124
Opened 2024-11-22 14:38 UTC by Gabeblis

This PR aims to add the missing leveraged authorization documentation to support PRs [#913](https://github.com/GSA/fedramp-automation/pull/913), [#921](https://github.com/GSA/fedramp-automation/pull/921), and [#927](https://github.com/GSA/fedramp-automation/pull/927).

2024-11-25 16:00 UTC, Gabeblis commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +If this system is leveraging the authorization of one or more systems, such as a SaaS running on an IaaS, each leveraged system must be represented within the system-implementation assembly. There mu
Thanks. I committed your suggestion. 👍

2024-11-27 21:11 UTC, DimitriZhurkin requested changes

2024-11-27 21:11 UTC, DimitriZhurkin commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +          <p>If 'no', explain why no authentication is used.</p>
Very minor, I'd change it slightly:
```suggestion
          <p>If 'no', explain why authentication is not used.</p>
```

2024-11-27 21:11 UTC, DimitriZhurkin commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +          <p>If 'not-applicable', attest explain why authentication is not applicable in the remarks.</p>
Remove `attest`?
```suggestion
          <p>If 'not-applicable', explain why authentication is not applicable in the remarks.</p>
```

2024-11-29 18:25 UTC, Gabeblis commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +        </remarks>
I committed your suggestion: [b15dbc6](https://github.com/GSA/automate.fedramp.gov/pull/124/commits/b15dbc6db8f8bccd3e788805532bb04066d12181)

2024-11-29 18:25 UTC, Gabeblis commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +          <p>If 'no', explain why no authentication is used.</p>
Thanks for the feedback. I removed these remarks. See: [b15dbc6](https://github.com/GSA/automate.fedramp.gov/pull/124/commits/b15dbc6db8f8bccd3e788805532bb04066d12181)

2024-11-29 18:40 UTC, aj-stein-gsa approved these changes

2024-12-02 14:44 UTC, DimitriZhurkin approved these changes

2024-12-02 15:57 UTC, merged