Add documentation for used-by links
GSA/automate.fedramp.gov pull request #133
Opened 2024-12-06 18:10 UTC by Gabeblis

## Purpose
This PR aims to add documentation for `used-by` links so that so that FedRAMP stakeholders understand what ports and protocols are being used by which during their risk assessment and what components are "used by" what components.

2024-12-06 18:40 UTC, DimitriZhurkin requested changes

2024-12-06 18:40 UTC, DimitriZhurkin commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +Entries in the ports, protocols, and services table are represented as component assemblies, with the component-type flag set to "service". Use a protocol assembly for each protocol associated with t
Just small suggestions. If you don't like them, ignore them.
```suggestion
Entries in the ports, protocols, and services table are represented as component assemblies, with the `type` flag set to "service". Use a protocol assembly for each protocol associated with the service. For a single port, set the port-range `start` and `end` flags to the same value. A component must reference the existing components that use it via network communication by including a `used-by` link to identify the component.
```

2024-12-09 16:36 UTC, Gabeblis commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +Entries in the ports, protocols, and services table are represented as component assemblies, with the component-type flag set to "service". Use a protocol assembly for each protocol associated with t
I appreciate the feedback, but I am going to resolve this since the feedback is on content that isn't part of the changes in this PR.

2024-12-10 15:46 UTC, aj-stein-gsa approved these changes

2024-12-10 17:10 UTC, DimitriZhurkin approved these changes

2024-12-10 17:15 UTC, merged