add documentation for issue 980 regarding last-accessed
GSA/automate.fedramp.gov pull request #142
Opened 2024-12-26 23:13 UTC by kyhu65867

This push adds in last-accessed versus published distinction into the back-matter resource section of the document, and provides an example of both.

2024-12-27 14:44 UTC, Gabeblis requested changes
Very detailed! Just one small thing I noticed with the description tags.

2024-12-27 14:44 UTC, Gabeblis commented on content/documentation/ssp/5-attachments.md
> +        <desc>Policy document</desc>
```suggestion
        <description>Policy document</description>
```

2024-12-27 14:44 UTC, Gabeblis commented on content/documentation/ssp/5-attachments.md
>          <desc>Policy document</desc>
```suggestion
        <description>Policy document</description>
```

2024-12-27 16:13 UTC, Gabeblis approved these changes

2024-12-30 14:44 UTC, wandmagic approved these changes

2024-12-30 14:44 UTC, merged