Feature website initial cleanup 3
GSA/automate.fedramp.gov pull request #24
Opened 2024-06-19 20:22 UTC by Rene2mt

Draft PR for issues listed in - https://github.com/GSA/automate.fedramp.gov/issues/21

2024-06-21 19:06 UTC, Rene2mt commented
This PR addresses core (high priority) parts of issues #21.

2024-06-24 01:05 UTC, david-waltermire commented on content/about/_index.md
> +title: About FedRAMP OSCAL
OSCAL is not FedRAMP's. This is about how FedRAMP is using OSCAL.
```suggestion
title: About FedRAMP's Use of OSCAL
```

2024-06-24 01:07 UTC, david-waltermire commented on content/documentation/_index.md
>  conversion.
YAML is just as supported as JSON and XML. This text needs to be revised.

2024-06-24 01:10 UTC, david-waltermire commented on content/documentation/_index.md
> +The [NIST OSCAL Build tools](https://github.com/usnistgov/OSCAL/blob/v1.1.2/build/README.md#schemas) provide a mechanism for validating OSCAL XML and JSON content. There are several open-source and c
Linking to a specifc version of OSCAL will not stand the test of time. Perhaps we can find a better, perhaps web-based, referemce.

2024-06-24 01:16 UTC, david-waltermire commented on content/documentation/general-concepts/oscal-data-types.md
> +
Please search for these and replace with the appropriate metaschema data type references?

2024-06-24 01:19 UTC, david-waltermire requested changes
References to OSCAL data types need to be replaced with the correct pages.nistgov/metaschema data type reference.

We should talk about how to reference specific OSCAL versions.

2024-06-24 19:16 UTC, Rene2mt commented on content/documentation/general-concepts/oscal-data-types.md
> +
Fixed in commit [a7d1f7e](https://github.com/GSA/automate.fedramp.gov/pull/24/commits/a7d1f7eaf05b39442543ce8691b31d049f19177f)

2024-06-24 21:21 UTC, Rene2mt commented on content/documentation/_index.md
>  conversion.
Revised section noting FedRAMP support of YAML in commit [b7d2ca6](https://github.com/GSA/automate.fedramp.gov/pull/24/commits/b7d2ca6a629e104e97d5ae4365af962695670962)

2024-06-24 22:10 UTC, Rene2mt commented on content/documentation/_index.md
> +The [NIST OSCAL Build tools](https://github.com/usnistgov/OSCAL/blob/v1.1.2/build/README.md#schemas) provide a mechanism for validating OSCAL XML and JSON content. There are several open-source and c
We could change this to one of the following:
- link refencing section on GitHub main branch - https://github.com/usnistgov/OSCAL/blob/main/build/README.md#schemas
- Permalink referencing section in GitHub - https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/build/README.md#schemas

OR we could update the links reference the following NIST pages:
- for validation - https://pages.nist.gov/OSCAL/resources/tools/#validation 
- for conversion - https://pages.nist.gov/OSCAL/resources/tools/#data-conversion

2024-06-25 12:27 UTC, david-waltermire commented on content/documentation/_index.md
> +The [NIST OSCAL Build tools](https://github.com/usnistgov/OSCAL/blob/v1.1.2/build/README.md#schemas) provide a mechanism for validating OSCAL XML and JSON content. There are several open-source and c
Please use the NIST pages.

2024-06-26 02:35 UTC, Rene2mt commented on content/documentation/_index.md
> +The [NIST OSCAL Build tools](https://github.com/usnistgov/OSCAL/blob/v1.1.2/build/README.md#schemas) provide a mechanism for validating OSCAL XML and JSON content. There are several open-source and c
Fixed in commit [edf56ce](https://github.com/GSA/automate.fedramp.gov/pull/24/commits/edf56ce07c4b253bf2afbb8c1382195425bda7d7)

2024-06-26 03:06 UTC, Rene2mt commented
Resolved review comments and suggestions, with exception of how to reference specific OSCAL versions.  Created issue #26 to address how to reference specific OSCAL versions of resources in various OSCAL related GitHub repositories.

2024-06-26 12:32 UTC, david-waltermire approved these changes

2024-06-26 12:32 UTC, merged