Release updated content for website
GSA/automate.fedramp.gov pull request #45
Opened 2024-08-30 18:15 UTC by aj-stein-gsa

Per discussion @david-waltermire, can you review the changes. And prompt dependency updates and example OSCAL content correction from a community member.

2024-08-30 18:15 UTC, aj-stein-gsa commented
**NOTE:** Per chatter with the FedRAMP Team, the broken link is a known issue and they will restore it. I am not sure how many days it will be, I did not get an ETA. Do you want to exempt the link explicitly and return it back later, or accept the build failure with the bad-link as-is, let me know, I am fine with either approach. I leave final decision with you. 🫡

2024-09-10 22:30 UTC, Rene2mt approved these changes

2024-10-01 13:10 UTC, Rene2mt approved these changes

2024-10-03 01:28 UTC, Rene2mt approved these changes

2024-10-18 14:49 UTC, kyhu65867 requested changes
A couple of minor things.

2024-10-18 14:49 UTC, kyhu65867 commented on content/about/faq.md
> +### Q: FedRAMP frequently provides OSCAL data in XML format? Does FedRAMP prefer OSCAL XML over OSCAL JSON or YAML?
Remove question mark after first sentence.

2024-10-18 14:49 UTC, kyhu65867 commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +<system-implementation>
Non-blocking-- we keep saying we are agnostic about data formats but then continue to only give examples in xml. I would recommend using oscal-cli or some equivalent-- https://jsonformatter.org/xml-to-json -- and then provide both json and yaml examples in a dropdown menu.

2024-10-18 14:49 UTC, kyhu65867 commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +<system-implementation>
![Screenshot 2024-10-18 at 10 42 05 AM](https://github.com/user-attachments/assets/39b597eb-8b86-443f-8e5b-c867ad8c4ccd)
Also I don't know if it's just my view but when I look at the markdown representation all of this code doesn't look good

2024-10-22 15:22 UTC, Gabeblis approved these changes
This looks solid. Just some minor, non-blocking grammatical issues that caught my eye.

2024-10-22 15:22 UTC, Gabeblis commented on content/about/faq.md
> +### Q: FedRAMP frequently provides OSCAL data in XML format? Does FedRAMP prefer OSCAL XML over OSCAL JSON or YAML?
Non-blocking: Minor adjustment for better flow. 
```suggestion
### Q: FedRAMP frequently provides OSCAL data in XML format. Does FedRAMP prefer OSCAL XML over OSCAL JSON or YAML formats?
```

2024-10-24 13:20 UTC, kyhu65867 approved these changes
Small feedback

2024-10-24 13:20 UTC, kyhu65867 commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +Each system must define at least two data centers. There must be exactly one primary data center, and there must be at least one alternate data center. Additionally, the country specified in the data
The apostrophe here and the fact that address is singular makes it seem like only one data center must be in the United States. It might be worth specifying that "both data centers' addresses must be in the United States".

2024-10-24 16:19 UTC, aj-stein-gsa commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +Each system must define at least two data centers. There must be exactly one primary data center, and there must be at least one alternate data center. Additionally, the country specified in the data
I am going to ask for that to be fixed in another PR specifically about data centers.

2024-10-24 17:02 UTC, Gabeblis commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +Each system must define at least two data centers. There must be exactly one primary data center, and there must be at least one alternate data center. Additionally, the country specified in the data
I fixed this in https://github.com/GSA/automate.fedramp.gov/pull/96. The only thing is that there can be more than 2 data centers, so I just made a simple change to make it clear that this applies to all data centers.

2024-10-24 17:16 UTC, aj-stein-gsa commented on content/about/faq.md
> +### Q: FedRAMP frequently provides OSCAL data in XML format? Does FedRAMP prefer OSCAL XML over OSCAL JSON or YAML?
Good catch.

```suggestion
### Q: FedRAMP frequently provides OSCAL data in XML format. Does FedRAMP prefer OSCAL XML over OSCAL JSON or YAML?
```

2024-11-12 22:39 UTC, aj-stein-gsa commented
Yeah sorry, I left this PR languishing too long. @david-waltermire is ok with the team and I deciding when to deploy and promote content, and there is no time like the present. :-)

2024-11-12 22:43 UTC, merged