Update requirements for SSP key roles and role POCs
GSA/automate.fedramp.gov pull request #60
Opened 2024-09-19 16:44 UTC by aj-stein-gsa

Closes #57.

2024-09-19 20:58 UTC, Rene2mt requested changes

2024-09-19 20:58 UTC, Rene2mt commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +A role with an ID value of "authorizing-official-poc" is required to identify a point of contact for an authorizing official. For the responsible-party of this role, it can be the same party as "auth
I agree that these should be required, however the latest Word SSP templates (see https://www.fedramp.gov/assets/resources/templates/FedRAMP-High-Moderate-Low-LI-SaaS-Baseline-System-Security-Plan-(SSP).docx) don't request or contain "authorizing official" or "authorizing official poc", so CSPs that are transitioning from legacy to OSCAL will need to fill the gap for this missing data.

This is not a blocking comment, just mentioning for awareness.

2024-09-19 20:58 UTC, Rene2mt commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +- The "system-poc-other" role is to identify a party responsible for system informational that is not technical or management related.
I'm not sure we should make all three of these required.  There will be cases where a CSP only has a technical POC, and other cases where they'll only have a management POC.   Perhaps, the requirement should be:

- at least one of the three roles (system-poc-management OR system-poc-technical OR system-poc-other) must be defined
- alternatively, we could say system-poc-management, system-poc-technical, and system-poc-other _**should**_ be provided

thoughts?

2024-09-19 21:03 UTC, Rene2mt commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +- The "system-poc-other" role is to identify a party responsible for system informational that is not technical or management related.
Also, system point of contact (e.g., system-poc-management, system-poc-technical, and system-poc-other roles) are not  the latest Word SSP templates (see https://www.fedramp.gov/assets/resources/templates/FedRAMP-High-Moderate-Low-LI-SaaS-Baseline-System-Security-Plan-(SSP).docx)  BUT I think these are valuable, which is why I'm recommending one of the two options in my comment above.

2024-09-19 21:45 UTC, aj-stein-gsa commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +A role with an ID value of "authorizing-official-poc" is required to identify a point of contact for an authorizing official. For the responsible-party of this role, it can be the same party as "auth
This is actually an excellent point and seems like to me a blocking comment. Let's circle back on this tomorrow and figure it out because I don't know how a LiSaaS system could not require an AO is that realistically possible?

2024-09-19 21:46 UTC, aj-stein-gsa commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +- The "system-poc-other" role is to identify a party responsible for system informational that is not technical or management related.
Also excellent feedback. I didn't find clear evidence either but thought I would push it up for discussion. Let's discuss tomorrow!

2024-09-20 17:49 UTC, aj-stein-gsa reviewed
I am now going to close this issue based on Rene's feedback and confirmation from internal reviewer and ConMon staff. [They confirmed](https://chat.google.com/room/AAAAk4y1ZQM/D8WoBM51zZk/D8WoBM51zZk?cls=10) the documented data, in OSCAL and Word format, is no longer used or needed.

Closing back on this comment.

2024-09-20 17:50 UTC, aj-stein-gsa commented
Closed based on the comment above.

2024-09-20 17:50 UTC, closed without merging