Add FedRAMP SSP requirements for user type, privilege, sensitivity
GSA/automate.fedramp.gov pull request #62
Opened 2024-09-20 01:55 UTC by aj-stein-gsa

Closes #44.

2024-09-20 01:57 UTC, aj-stein-gsa commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +**FedRAMP Extension:**
Note: @Rene2mt I do not like the structure of repeat bold extension, extension value listing. We did not worry about this until now, if I could guess, because we have only had one custom extension field/flag/assembly extension point and value out at a time per callout box. Not sure if it is important to fix now or defer for a redesign, but I would like to call out I too dislike this approach.

2024-10-02 14:29 UTC, Rene2mt requested changes

2024-10-02 14:29 UTC, Rene2mt commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +- not-applicable
```suggestion
**OSCAL prop**
- name="type"

**OSCAL Allowed Values**

- internal
- external
- general-public

---

**OSCAL prop**
- name="privilege-level"

**OSCAL Allowed Values**

- privileged
- non-privileged
- no-logical-access

---

**FedRAMP Extension:**

prop (ns=“https://fedramp.gov/ns/oscal")
- name="sensitivity"

**FedRAMP Allowed Values**

- high-risk
- severe
- moderate
- limited
- not-applicable

---

**FedRAMP Extension:**

prop (ns=“https://fedramp.gov/ns/oscal")
- name="authentication-method"

**FedRAMP Allowed Values**

Values for `authentication-method` are not constrained.  However, SSP authors should provide values that are consistent with the authentication types identified in [NIST SP 800-63B](https://pages.nist.gov/800-63-3/sp800-63b.html#63bSec4-Table1).

```

2024-10-03 20:25 UTC, Rene2mt approved these changes

2024-10-03 20:53 UTC, merged