Stage folder structure and info for automation meetings
GSA/automate.fedramp.gov pull request #73
Opened 2024-10-03 17:57 UTC by aj-stein-gsa

This is part of GSA/fedramp-automation#738.

We need to remove presentation material from previous locations and place them here before closing and archiving the others.

To do so, we need this area of the repository to exist.

2024-12-02 21:01 UTC, Rene2mt requested changes
The data bytes and early adopters pages look good.  Made some suggestions fro the OSCAL Implementer page.

2024-12-02 21:13 UTC, aj-stein-gsa commented on content/collaborate/meetings/implementers/_index.md
> +---
Ha! I swore I added this locally and in my pre-flight stupor before going on leave, I didn't even include this!? I hope I have it stashed locally, I will go check.

2024-12-03 13:39 UTC, aj-stein-gsa commented on content/collaborate/meetings/implementers/_index.md
> +---
I found it @Rene2mt and updated in https://github.com/GSA/automate.fedramp.gov/pull/73/commits/e773c8bb74c71eec6ef4bad4914c2d2d6911ee27. I used this commit and not your suggestion because I had taken time to pattern out all the attachments in the list, so we do not have to say coming soon after all. 😄

2024-12-04 18:46 UTC, Rene2mt approved these changes

2024-12-05 18:24 UTC, Gabeblis approved these changes
LGTM

2024-12-05 18:29 UTC, merged