Add data center documentation
GSA/automate.fedramp.gov pull request #85
Opened 2024-10-17 14:40 UTC by Gabeblis

## Description
Added documentation regarding data centers. This documentation includes a description of requirements/expectations, an XML example of the requirements/expectations, and some helpful XPath queries.

2024-10-17 22:00 UTC, Rene2mt submitted a review, later dismissed

2024-10-17 22:00 UTC, Rene2mt commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +        /*/metadata/location[prop[@value eq 'data-center']]/address/country eq 'US'
Need to key off of the `prop` name

```suggestion
    Number of Data Centers:
        count(/*/metadata/location[prop[@name eq 'data-center']]) > 1
        count(/*/metadata/location[prop[@name eq 'data-center']]) > 1
    Number of Primary Data Centers:
        count(/*/metadata/location/prop[@name eq 'data-center'][@class eq 'primary']) = 1
    Number of Alternate Data Centers:
        count(/*/metadata/location/prop[@name eq 'data-center'][@class eq 'alternate']) > 0
    Data Center Country:
        /*/metadata/location[prop[@name  eq 'data-center']]/address/country = 'US'
```

2024-10-18 01:24 UTC, Gabeblis commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +        /*/metadata/location[prop[@value eq 'data-center']]/address/country eq 'US'
> Need to key off of the `prop` name

Thank you for catching that. Resolved, see: 570af5c1a5ff1c6e651fc6a143a9c954a8474070

2024-10-18 01:25 UTC, Gabeblis commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +       <prop name='data-center' value='some-location-value' class='primary' ns="https://fedramp.gov/ns/oscal"/>
Thank you for the explanation. Resolved, see: 570af5c1a5ff1c6e651fc6a143a9c954a8474070

2024-10-18 01:25 UTC, Gabeblis commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +---
Resolved, see: 570af5c1a5ff1c6e651fc6a143a9c954a8474070

2024-10-18 01:27 UTC, Gabeblis commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +       <prop name='data-center' value='some-location-value' class='alternate' ns="https://fedramp.gov/ns/oscal"/>
Resolved: 570af5c1a5ff1c6e651fc6a143a9c954a8474070

2024-10-18 04:30 UTC, aj-stein-gsa requested changes
Nice work, if you can clean up the two errors in the examples, I will be comfortable approving when you request re-review. I _may_ ask for feedback from internal staff about where the higher-level requirement comes from outside of OSCAL as well, because it would seem that is important. (I have been unable to track this down as of late.)

2024-10-18 04:30 UTC, aj-stein-gsa commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +          <country>us</country>
Blocking: [ISO 3166 Alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2), which this constraint requires (and is explained in the upstream OSCAL documentation from NIST), ought to be capitalized, not lower case. If you run these examples through the constraints test harness it should fail.

```suggestion
          <country>US</country>
```

2024-10-18 04:30 UTC, aj-stein-gsa commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +          <country>us</country>
Blocking: [ISO 3166 Alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2), which this constraint requires (and is explained in the upstream OSCAL documentation from NIST), ought to be capitalized, not lower case. If you run these examples through the constraints test harness it should fail.

```suggestion
          <country>US</country>
```

2024-10-18 04:33 UTC, Gabeblis commented
> Nice work, if you can clean up the two errors in the examples, I will be comfortable approving when you request re-review. I _may_ ask for feedback from internal staff about where the higher-level requirement comes from outside of OSCAL as well, because it would seem that is important. (I have been unable to track this down as of late.)

Thank you for the review

2024-10-18 04:37 UTC, aj-stein-gsa approved these changes

2024-10-18 12:26 UTC, Rene2mt submitted a review, later dismissed

2024-10-18 12:26 UTC, Rene2mt commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +Each system must define at least two data centers. There must be exactly one primary data center, and there must be at least one alternate data center. Additionally, the country specified in the data
The example shows "US" but if we don't explicitly callout that they must use [ISO 3166 Alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2), people are likely to input other things that will not pass our validation checks (e.g., "United States", "USA", "usa", "us").

```suggestion
Each system must define at least two data centers. There must be exactly one primary data center, and there must be at least one alternate data center. Additionally, the country specified in the data center's address must be the United States, and must be in [ISO 3166 Alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) two-letter country code format (e.g., "US" in all upper case).
```

All other changes look great!!!

2024-10-18 12:27 UTC, Rene2mt commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +Each system must define at least two data centers. There must be exactly one primary data center, and there must be at least one alternate data center. Additionally, the country specified in the data
btw, sorry for not submitting this change with prior review...I had start do but between meetings must have submitted my review without posting this suggestion

2024-10-18 12:31 UTC, Rene2mt commented
> Nice work, if you can clean up the two errors in the examples, I will be comfortable approving when you request re-review. I _may_ ask for feedback from internal staff about where the higher-level requirement comes from outside of OSCAL as well, because it would seem that is important. (I have been unable to track this down as of late.)

@aj-stein-gsa  I believe this requirement comes from baseline controls CP-7 (alternate processing site) and CP-7(1) (separation from primary site).

2024-10-18 13:16 UTC, Rene2mt approved these changes

2024-10-18 13:23 UTC, aj-stein-gsa approved these changes
Minor nit based on the conversation between you and @Rene2mt. Slight change, take it or leave it.

2024-10-18 13:23 UTC, aj-stein-gsa commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +Each system must define at least two data centers. There must be exactly one primary data center, and there must be at least one alternate data center. Additionally, the country specified in the data
Sorry to come and be annoying because I am a few minutes behind, perhaps point to the official OSCAL model docs that explained this to me, not Wikipedia? I did that as a tl;dr casually among developers, and much of the data is exhaustive. Or maybe it is useful, I don't know.

```suggestion
Each system must define at least two data centers. There must be exactly one primary data center, and there must be at least one alternate data center. Additionally, the country specified in the data center's address must be the United States, and must be in [ISO 3166 Alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) two-letter country code format (e.g., "US" in all upper case).

```suggestion
Each system must define at least two data centers. There must be exactly one primary data center, and there must be at least one alternate data center. Additionally, the country specified in the data center's address must be the United States. It must be in [ISO 3166 Alpha-2 format](https://pages.nist.gov/OSCAL-Reference/models/v1.1.2/system-security-plan/xml-reference/#/system-security-plan/metadata/location/address/country) two-letter country code format (e.g., "US" in all upper case).
```

2024-10-18 13:27 UTC, Gabeblis commented
> Minor nit based on the conversation between you and @Rene2mt. Slight change, take it or leave it.

Thank you, I committed the suggestion.

2024-10-18 14:51 UTC, kyhu65867 approved these changes
This looks good :)

2024-10-22 14:04 UTC, merged