Add information type documentation
GSA/automate.fedramp.gov pull request #87
Opened 2024-10-18 12:34 UTC by Gabeblis

## Description
Added documentation regarding information type. This documentation includes a description of some requirements/expectations, an XML example of the requirements/expectations, allowed values, and some helpful XPath queries.

2024-10-18 14:57 UTC, Gabeblis commented
> Hey, there's overlap between this PR and PR #56 which is pending review 😄

It definitely looks that way. The documentation in this PR could definitely be added to https://github.com/GSA/automate.fedramp.gov/pull/56.

2024-10-29 13:23 UTC, Rene2mt approved these changes
Looks good to me.  Nice work!

2024-10-29 13:27 UTC, aj-stein-gsa requested changes

2024-10-29 13:27 UTC, aj-stein-gsa commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +The `system-information` assembly and its defined `information-type` assemblies are used to document all of the information types that are either stored, processed, or transmitted by the system. The
It seems you improved this as I reviewed, but maybe slight wording adjustments and use the official DOI links.

```suggestion
The `system-information` assembly and its defined `information-type` assemblies identify all of the information types that the system stores, processes, or transmits. FedRAMP requires digital authorization packages always use [the NIST SP 800-60 categorization system](https://doi.org/10.6028/NIST.SP.800-60v2r1) for information types. 
```

2024-10-29 13:27 UTC, aj-stein-gsa commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +The `categorization` assembly captures the set of defined information types, which must be sourced from [NIST SP 800-60](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-60v2r1.p
This is a little redundant with the above maybe align it a little?

```suggestion
FedRAMP requires the  `categorization` for each `information-type` to identify the `information-type-id` with IDs. Because FedRAMP requires [the NIST SP 800-60 categorization system](https://doi.org/10.6028/NIST.SP.800-60v2r1) for digital authorization packages, the `system` for each `information-type-id` must be `"https://doi.org/10.6028/NIST.SP.800-60v2r1"`.
```

2024-10-29 15:32 UTC, Gabeblis commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +The `categorization` assembly captures the set of defined information types, which must be sourced from [NIST SP 800-60](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-60v2r1.p
'twas a bit redundant. Thank you for the adjustment

2024-10-29 15:32 UTC, Gabeblis commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +The `system-information` assembly and its defined `information-type` assemblies are used to document all of the information types that are either stored, processed, or transmitted by the system. The
Good catch 👍

2024-10-29 16:11 UTC, aj-stein-gsa approved these changes

2024-10-29 16:22 UTC, DimitriZhurkin requested changes

2024-10-29 16:22 UTC, DimitriZhurkin commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +FedRAMP requires the  `categorization` for each `information-type` to identify the `information-type-id` with IDs. Because FedRAMP requires [the NIST SP 800-60 categorization system](https://doi.org/
Just a quick observation: `FedRAMP requires` is repeated over and over again in these two opening paras.

Maybe replace `FedRAMP requires the  categorization...` with `Each information-type must have...`, or something like that.

2024-10-29 16:36 UTC, Gabeblis commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +FedRAMP requires the  `categorization` for each `information-type` to identify the `information-type-id` with IDs. Because FedRAMP requires [the NIST SP 800-60 categorization system](https://doi.org/
Thank you for the feedback. Resolved: 8e76949d269ee6bf464e155899c5f06b069a909a

2024-10-29 16:37 UTC, DimitriZhurkin approved these changes

2024-10-29 17:17 UTC, merged