Add documentation for security-sensitivity-level
GSA/automate.fedramp.gov pull request #91
Opened 2024-10-22 14:37 UTC by Gabeblis

## Description 

Added documentation regarding the security sensitivity level. This documentation includes a description of requirements/expectations, an XML example of the requirements/expectations, and some important notes.

2024-10-23 12:50 UTC, aj-stein-gsa requested changes

2024-10-23 12:50 UTC, aj-stein-gsa commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +The privacy system designation in the FedRAMP SSP template, illustrated in the figure below, is expressed through the following core OSCAL property. Specifically, a FedRAMP SSP must define its FIPS-1
I believe @Rene2mt called this out yesterday in the paired constraint PR review, but I thought it was a should, not a must.

```suggestion
The privacy system designation in the FedRAMP SSP template, illustrated in the figure below, is expressed through the following core OSCAL property. Specifically, a FedRAMP SSP should define its FIPS-199 system sensitivity level as one of the allowed values below, and it should match the highest security impact level for the system’s confidentiality, integrity, and availability objectives.
```

2024-10-23 14:15 UTC, kyhu65867 requested changes
Slight tweak

2024-10-23 14:15 UTC, kyhu65867 commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +The privacy system designation in the FedRAMP SSP template, illustrated in the figure below, is expressed through the following core OSCAL property. Specifically, a FedRAMP SSP must define its FIPS-1
Not your fault, just a nature of the way this was initially structured, but I think this section could be streamlined to be more concise and clear. "The privacy system designation in the FedRAMP SSP template, shown in the figure below, can be expressed through a core OSCAL property that specifies the FIPS-199 sensitivity level based on the highest security impact for confidentiality, integrity, and availability."

2024-10-23 21:16 UTC, DimitriZhurkin reviewed
Absolutely not a blocker, but I think `the figure below` should be `the table below`. Otherwise, looks good to me.

2024-10-24 03:52 UTC, Gabeblis commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +The privacy system designation in the FedRAMP SSP template, illustrated in the figure below, is expressed through the following core OSCAL property. Specifically, a FedRAMP SSP must define its FIPS-1
Noted and change applied. Thank you.

2024-10-24 04:03 UTC, Gabeblis commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +The privacy system designation in the FedRAMP SSP template, illustrated in the figure below, is expressed through the following core OSCAL property. Specifically, a FedRAMP SSP must define its FIPS-1
Thank you for the feedback. Addressed: 978cf11585c6b1ec8c6ad3ae74547a9310a65ce8

2024-10-24 04:24 UTC, aj-stein-gsa reviewed
Have I been so slow on another PR that we are writing against the same gap in the system characteristics?

https://github.com/GSA/automate.fedramp.gov/pull/56#pullrequestreview-2382601190

2024-10-24 04:44 UTC, Gabeblis commented
> Have I been so slow on another PR that we are writing against the same gap in the system characteristics?
> 
> [#56 (review)](https://github.com/GSA/automate.fedramp.gov/pull/56#pullrequestreview-2382601190)

Fun. There is definitely a little overlap here, but there is new information being added. I can definitely work on merging this into the existing PR, and getting that to a good state.

2024-10-24 04:46 UTC, aj-stein-gsa commented
> > Have I been so slow on another PR that we are writing against the same gap in the system characteristics?
> 
> > 
> 
> > [#56 (review)](https://github.com/GSA/automate.fedramp.gov/pull/56#pullrequestreview-2382601190)
> 
> 
> 
> Fun. There is definitely a little overlap here, but there is new information being added. I can definitely work on merging this into the existing PR, and getting that to a good state.

I'm fine either way. I've been too slow and it's catching up with me and the scope of that issue was vague. So ... I broke my own principles there. Feel free to repoint to my branch if you want.

2024-10-24 13:09 UTC, kyhu65867 approved these changes
Looks good to me! Thanks for the hard work :)

2024-10-24 13:09 UTC, kyhu65867 commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +The privacy system designation in the FedRAMP SSP template, illustrated in the figure below, can be expressed through a core OSCAL property that defines its FIPS-199 system sensitivity level as one o
I like this wording a lot better

2024-10-25 13:42 UTC, Rene2mt requested changes
PR changes look good.  Added a suggestion to fix a small pre-existing issue while we're updating this section

2024-10-25 13:42 UTC, Rene2mt commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +The privacy system designation in the FedRAMP SSP template, illustrated in the figure below, can be expressed through a core OSCAL property that defines its FIPS-199 system sensitivity level as one o
Just noticed the site has a minor error here, so we can fix it while we're updating this section.

```suggestion
The FIPS PUB 199 level designation in the FedRAMP SSP template, illustrated in the figure below, can be expressed through a core OSCAL property that defines its FIPS-199 system sensitivity level as one of the allowed values below. The FIPS-199 system sensitivity level should match the highest security impact level for the system’s confidentiality, integrity, and availability objectives.
```

2024-10-25 15:56 UTC, DimitriZhurkin approved these changes

2024-10-25 17:31 UTC, Rene2mt approved these changes

2024-10-28 12:53 UTC, aj-stein-gsa commented
@Gabeblis I am really sorry I did not review it on Friday. Thanks for pinging me again. I actually did not complete a review then, but no time like the present. I gave some feedback.

2024-10-28 14:14 UTC, Gabeblis commented
> @Gabeblis I am really sorry I did not review it on Friday. Thanks for pinging me again. I actually did not complete a review then, but no time like the present. I gave some feedback.

Thank you for the feedback sir

2024-10-28 14:15 UTC, DimitriZhurkin commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +The FIPS PUB 199 level designation in the FedRAMP SSP template, illustrated in the figure below, can be expressed through a core OSCAL property that defines its FIPS-199 system sensitivity level as o
Sorry, but I personally find it rather difficult to read and understand.

2024-10-28 14:29 UTC, aj-stein-gsa commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +The FIPS PUB 199 level designation in the FedRAMP SSP template, illustrated in the figure below, can be expressed through a core OSCAL property that defines its FIPS-199 system sensitivity level as o
Do you have a specific suggestion on how you would edit it then?

2024-10-28 18:18 UTC, DimitriZhurkin commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +The FIPS PUB 199 level designation in the FedRAMP SSP template, illustrated in the figure below, can be expressed through a core OSCAL property that defines its FIPS-199 system sensitivity level as o
Just a quick hack:

A FedRAMP SSP defines the system's sensitivity level in `security-sensitivity-level`. The supporting information for the sensitivity level is specified in `security-impact-level`.

The value of `security-sensitivity-level` should match the highest security level specified in `security-impact-level` (`security-objective-confidentiality`, `security-objective-integrity`, and `security-objective-availability`).

For example, if the highest `security-impact-level` value is `fips-199-moderate`, the `security-sensitivity-level` value should be `fips-199-moderate`.

2024-10-28 20:24 UTC, kyhu65867 requested changes

2024-10-28 20:24 UTC, kyhu65867 commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +A FedRAMP SSP in OSCAL defines the system's sensitivity level and supporting information with `security-sensitivity-level` and `security-impact-level` adjacent to one another, not in a separate attac
Adjacent to me sounds like side-by-side. I would say consecutively but I think that word may not be the most accessible so for Plain Language sake I would say "A FedRAMP SSP in OSCAL defines the system's sensitivity level and supporting information with 'security-sensitivity-level' directly followed by 'security-impact-level', NOT in a separate attachment....."

2024-10-29 06:25 UTC, Gabeblis commented on content/documentation/ssp/4-ssp-template-to-oscal-mapping.md
> +A FedRAMP SSP in OSCAL defines the system's sensitivity level and supporting information with `security-sensitivity-level` and `security-impact-level` adjacent to one another, not in a separate attac
I see how the wording is a little misleading here. Resolved: 948dcd1a78b5afb18b03765cd3b11f25bfd4bd39

2024-10-29 12:25 UTC, aj-stein-gsa approved these changes

2024-10-29 17:14 UTC, kyhu65867 approved these changes
This looks better and more clear, thanks!

2024-10-29 17:18 UTC, merged